server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://180.76.235.69:3306/hardware-ai?serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: aY)I&iBop[F3t
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  redis:
    ## Redis数据库索引（默认为0）
    database: 1
    host: 192.168.0.2
    port: 6379
    password: 'aY)I&ikkop[F3t'
socket:
  # 监听端口 9999
  port: 20000
  #ip地址
  host:  192.168.0.2