spring:
  application:
    name: iot-netty
  profiles:
    active: dev
    group:
      dev:
        - dev
#        - local
      pro:
        - pro
  mvc:
    servlet:
      load-on-startup: 1

mybatis-plus:
  mapperLocations: classpath:mappers/**/*.xml

mybatis:
  # 搜索指定包别名
#  typeAliasesPackage: com.yh.gen.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mappers/**/*.xml


#logging:
#  level:
#    root: info

springdoc:
  packagesToScan: com.NettyApplication.controller
  swagger-ui:
    path: /swagger/index.html
    enabled: true
  api-docs:
    path: /swagger/api-docs
    enabled: true