server:
  port: 8888
spring:
  redis:
    ## Redis数据库索引（默认为0）
    database: 2
    host: 180.76.235.69
    port: 6379
    password: 'aY)I&ikkop[F3t'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///hardware-ai?serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
socket:
  # 监听端口 9999
  port: 20000
  #ip地址
  host: 127.0.0.1
#
#  profiles:
#    active: dev



